language: go
go:
  - 1.1
env:
  - DOCKR_HOST=unix:///var/run/docker.sock
before_install:
  - sudo sh -c "wget -O - http://get.docker.io/gpg | apt-key add -"
  - sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
  - sudo apt-get update
  - go get github.com/mattn/gom
install:
  - sudo apt-get install --yes lxc-docker
  - sudo docker pull ubuntu:precise
  - $HOME/gopath/bin/gom install
script:
  - $HOME/gopath/bin/gom test
